### ISSUE TITLE
TypeError: jQuery(...).gmap3 is not a function

### ISSUE THREAD

**Issue by mhenden** [i-lateral/silverstripe-googlemaps#5]
I've used this module before with no problems. However on the site I am working on I'm getting the aforementioned error. I don't know if it's a script loading issue (I believe gmap3 needs JScript already loaded in order to run) and I've tried loading it from a few different places with the same result. Or it could be a conflict? Anybody seen this? Were you able to solve it?

**Comment by mlewis-everley** [comment]
Closing this issue as should now be fixed...
