### ISSUE TITLE
'Map loading...'

### ISSUE THREAD

**Issue by mhenden** [i-lateral/silverstripe-googlemaps#6]
It isn't. 

I have module loaded, works in CMS, have requested and set up API key, etc but map is simply NOT loading. Did I miss anything?

**Comment by mlewis-everley** [comment]
So this issue is very old. I have done a fairly major update and merged in a lot of old pull requests.

I am not getting the map loading error any more, does the update fix your issues?

**Comment by mlewis-everley** [comment]
I am closing this issue, as there has been no response in quite some time.
